[package]
name = "xs_bevy_core_2d"
version = "0.1.0"
edition = "2021"
org = "xsware"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7.0"
lazy_static = "1.4.0"
